name: Dispatch to Repo B 

on:
  workflow_dispatch: 
  push:
    branches:
      - main  # or your desired branch

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in Repo B
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: siddharthanelango/check3
          event-type: trigger-from-repo-a
          client-payload: '{"ref": "${{ github.ref }}", "pusher": "${{ github.actor }}"}'
